### ISSUE TITLE
Leitura dos dados

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/dig-tools-bahia#10]
- [x] Reler o [relatório final](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/tree/main/Relatorios)
- [x] Avaliar os [dados do questionário](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/tree/main/dados)
- [x] escrever apontamentos e ideias gerais
- [x] reunião para debate

**Comment by priscilavalverdes** [comment]
Ciente!
