### ISSUE TITLE
Finalização do artigo

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/dig-tools-bahia#11]
Finalizar o artigo até dia **21/12/2023** para enviar para o dossiê  [**História Digital: tecnologia e fazer historiográfico entre teoria e prática** da Revista Locus](https://periodicos.ufjf.br/index.php/locus/announcement/view/719).

- [x] Revisar a Introdução
- [x] Revisar a Revisão da literatura
- [x] Revisar a Metodologia
- [x] Revisar Resultados
- [x] Escrever o tópico *Pensando o presente e o futuro da disciplina*
- [x] Escrever a *Conclusão*
- [x] Revisar formatação para a [revista Locus](https://periodicos.ufjf.br/index.php/locus/about/submissions)

**Comment by priscilavalverdes** [comment]
@ericbrasiln , vc acha que seria interessante se definíssemos o conceito de "seletividade digital"?

**Comment by ericbrasiln** [comment]
Acho que sim, mas pelo caminho que o artigo está tomando acho que nem vamos conseguir usar ele como fio condutor e talvez tenhamos que mudar.

**Comment by priscilavalverdes** [comment]
@ericbrasiln , coloquei meu esboço do tópico "Pensando o presente e o futuro da disciplina" no doc para você ver mas ainda vou mexer nele.
